name: Update README and Index Version

on:
  push:
    paths:
      - "version.json"
  workflow_dispatch:

jobs:
  update-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: updates

      - name: Read version.json
        id: get_version
        run: echo "VERSION=$(jq -r '.version' version.json)" >> $GITHUB_ENV

      - name: Replace version in README.md
        run: sed -i "s|{{VERSION}}|${{ env.VERSION }}|g" README.md

      - name: Replace version in index.html
        run: sed -i "s|{{VERSION}}|${{ env.VERSION }}|g" index.html

      - name: Commit and push changes to updates branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md index.html
          git commit -m "Update version text to ${{ env.VERSION }}" || echo "No changes to commit"
          git push origin updates

      - name: Merge updates into main
        run: |
          git fetch origin main
          git checkout main
          git pull origin main
          git merge --no-ff updates -m "Merging updates into main"
          git push origin main
